- docs/guide/dep-pre-bundling.md
resolves #10
Cherry picked from https://github.com/vitejs/vite/commit/33f96718dc5d827612c300fb6d0258f1c040f5a1
> docs: update pre-bundling guide (#10)

- .gitignore
- docs/guide/index.md
- docs/guide/why.md
Added to `.gitignore` exclusions for `IntelliJ/Webstorm` stuff
> docs(revision): `why` and `index`

- docs/config/index.md
resolves #16
Cherry picked from https://github.com/vitejs/vite/commit/76bbcd09985f85f7786b7e2e2d5ce177ee7d1916
> docs: add config env var info (#16)

- docs/guide/dep-pre-bundling.md
resolves #19
Cherry picked from https://github.com/vitejs/vite/commit/b81e1a289f20a4ba2396f11939646407a67bbf0e
> docs: explain dep handling in dev and build (#19)

- docs/guide/features.md
resolves #23
Cherry picked from https://github.com/vitejs/vite/commit/3070ecb12d9a4eebf607128ca8acbdb9aecf5404
> docs: glob support alias path (#23)

- docs/guide/build.md
resolves #27
Cherry picked from https://github.com/vitejs/vite/commit/7dcf370d0f27ef7d5073006fcd943ab9083cabe1
> docs(build): fix chunking strategy info (#27)

- docs/config/index.md
resolves #29
Cherry picked from https://github.com/vitejs/vite/commit/6608bd04af033717184cfff0074b2d9661db8804
> docs: clarify postcss-load-config (#29)

- docs/config/index.md
resolves #31
Cherry picked from https://github.com/vitejs/vite/commit/c6c2fbbd9f647070d8e295eab3eda135990ad07e
> docs: clarify preprocessor options extension (#31)

- docs/config/index.md
resolves #33
Cherry picked from https://github.com/vitejs/vite/commit/c2ab324a5def68475acc444e781e03094692ca84
> docs: add missing server.headers + server.base (#33)

- docs/guide/backend-integration.md
resolves #35
Cherry picked from https://github.com/vitejs/vite/commit/bf57c5398937cfc307171c7dcc658727575b004b
> docs: remove vite client script (#35)

- docs/config/index.md
resolves #40
Cherry picked from https://github.com/vitejs/vite/commit/fe85d089840f4fe112042d2a2abdbbe39280242f
> docs: note esbuild picomatch pattern (#40)

- docs/config/index.md
resolves #48
Cherry picked from https://github.com/vitejs/vite/commit/81d7dd256aa08a8de257fd5bc397980a99d279a9
> docs: add css.devSourcemap option (#48)

- docs/guide/env-and-mode.md
resolves #52
Cherry picked from https://github.com/vitejs/vite/commit/884e994b7322eb4ff96f457fe536affcd0b596d0
> docs: note env in command line (#52)

- docs/guide/env-and-mode.md
resolves #58
Cherry picked from https://github.com/vitejs/vite/commit/b16b8964e633cbf1ee2b051044af2660f1636558
> docs: add wildcard to suggested .gitignore entry in docs (#58)

- docs/config/index.md
resolves #56
Cherry picked from https://github.com/vitejs/vite/commit/4d5521854c0b7213ec7d061dedd7f34e54919944
> docs: declare the scope of define expressions (#56)

- docs/guide/api-plugin.md
resolves #62
Cherry picked from https://github.com/vitejs/vite/commit/a89ea5202e9492c2b60598b6b8095ecf31dafbd8
> docs: update plugin example (#62)

- docs/guide/api-plugin.md
resolves #64
Cherry picked from https://github.com/vitejs/vite/commit/c02537b5b2ac5e39313601cc22530ef6201239b9
> docs: improve virtual module examples (#64)

- docs/guide/assets.md
resolves #66
Cherry picked from https://github.com/vitejs/vite/commit/09c4fc01a83b84f77b7292abcfe7500f0e948db6
> docs: warning for `new URL(url, import.meta.url)` (#66)

- docs/guide/features.md
resolves #71
Cherry picked from https://github.com/vitejs/vite/commit/788d2ec1dc9853be4ecdef67d1a458a2b46ec9bf
> docs: explain skipLibCheck (#71)

- docs/guide/api-hmr.md
resolves #78
Cherry picked from https://github.com/vitejs/vite/commit/72abe488b5ce52d21977c9ba35d6c590e47dbe05
> docs(api-hmr): update hmr hot type (#78)

- docs/guide/features.md
resolves #80
Cherry picked from https://github.com/vitejs/vite/commit/3edd1af56e980aef56641a5a51cf2932bb580d41
> docs: update link to postcss-nesting repo (#80)

- docs/config/index.md
resolves #83
Cherry picked from https://github.com/vitejs/vite/commit/206e1f2cd48b86396f57338ad494da3e1939b647
> docs: clarify loadEnv (#83)

- docs/blog/announcing-vite2.md
Translation of blog/announcing-vite2.md
> docs: translating the file in blog folder

- docs/config/index.md
resolves #97
Cherry picked from https://github.com/vitejs/vite/commit/095543fcc5fd978e8b56fd68a7bc1785db339ee7
> docs: note for inconsistency between dev and build (#97)

- docs/config/index.md
resolves #99
Cherry picked from https://github.com/vitejs/vite/commit/b2c029a086de135bbb04bbe0e35c0a3b4526900e
> docs: mention middlewares in server.proxy config (#99)

- docs/config/index.md
resolves #136
Cherry picked from https://github.com/vitejs/vite/commit/ed12ed1b1d40ae106fdc9403fd581f316b20f560
> docs: update config jsdoc style (#136)

- docs/.vitepress/config.ts
resolves #159
Cherry picked from https://github.com/vitejs/vite/commit/d9123995d440599e9ef2bb85b8f5d0fbe3dc7b1d
> docs: link to es translation (#159)

- docs/.vitepress/theme/styles/vars.css
resolves #191
Cherry picked from https://github.com/vitejs/vite/commit/5340005fc01ae536a077103f64b92f6e51bcec34
> docs: fix link a11y (#191)

- docs/.vitepress/config.ts
resolves #206
Cherry picked from https://github.com/vitejs/vite/commit/8e0308bee847e5a1a126a86585ff102583e81c3c
> docs: add `appId` in vitepress config (#206)

- docs/guide/ssr.md
resolves #213
Cherry picked from https://github.com/vitejs/vite/commit/cc980b09444f67bdcd07481edf9e0c0de6b9b5bd
> docs: __dirname is not available in ES modules (#213)

- docs/guide/troubleshooting.md
resolves #243  
Translated text from [vitejs/vite@`e8b61bb`](https://github.com/vitejs/vite/commit/e8b61bb3cac6c9c3ef3fa33e43440cc646473696)
> feat: show warning on 431 response (#243)

- docs/guide/ssr.md
resolves #247 
Translated text from [vitejs/vite@`095e920`](https://github.com/vitejs/vite/commit/095e92041ebe638da95ae8d507d13a34d8f63f62)
> docs(ssr): note linked deps no external (#247)

- docs/guide/api-javascript.md
resolves #258 
Translated text from [vitejs/vite@`c3f6731`](https://github.com/vitejs/vite/commit/c3f6731bafeadd310efa4325cb8dcc639636fe48)
> feat: stabilize server.resolvedUrls (#258)

- docs/guide/features.md
> fix issue #399

- docs/guide/cli.md
resolves https://github.com/vitejs/docs-es/issues/401
> fix issue #401

- docs/guide/api-plugin.md
resolves https://github.com/vitejs/docs-es/issues/400
> fix issue #400

- docs/.vitepress/config.ts
resolves https://github.com/vitejs/docs-es/issues/416
> fix issue #416

- docs/.vitepress/theme/styles/vars.css
resolves https://github.com/vitejs/docs-es/issues/408
> fix issue #408

- docs/guide/index.md
resolves https://github.com/vitejs/docs-es/issues/403
> fix: issue #403

- docs/config/index.md
resolves https://github.com/vitejs/docs-es/issues/418
> fix: issue #418

- docs/guide/build.md
resolves https://github.com/vitejs/docs-es/issues/404
> fix: issue #404

- docs/config/server-options.md
Hi, I have deleted the config.server.base, described in the problem #428
> fix: remove deprecated config.server.base

- docs/config/dep-optimization-options.md
resolves https://github.com/vitejs/docs-es/issues/402
> docs: optimizeDeps.needsInterop #402

- docs/guide/troubleshooting.md
resolves https://github.com/vitejs/docs-es/issues/405
> docs: cross drive links troubleshooting guide #405

- docs/config/server-options.md
resolves https://github.com/vitejs/docs-es/issues/406
> docs: accessing the server on WSL2 from your LAN #406

- docs/guide/build.md
solves https://github.com/vitejs/docs-es/issues/413
> docs(chunkSplitting): add manualChunks object form syntax warning ... #413

- docs/config/index.md
> docs: note config support ts extension #441

- docs/guide/api-javascript.md
> fix(mergeConfig): don't accept callback config #409

- docs/guide/api-hmr.md
> feat(client): add WebSocket connections events #431

- docs/config/dep-optimization-options.md
> feat(optimizer): support glob includes #415

- docs/config/server-options.md
> feat: support files for fs.allow #411

- docs/guide/troubleshooting.md
> feat(config): friendly ESM file require error #410

- docs/config/build-options.md
- docs/config/shared-options.md
- docs/guide/features.md
Solves #444 
and also #450 and #452
> docs: experimental Lightning CSS support #444

- docs/guide/index.md
> feat(create-vite): add solidjs templates #455

- docs/config/build-options.md
- docs/config/dep-optimization-options.md
- docs/config/shared-options.md
- docs/config/ssr-options.md
- docs/guide/build.md
Hi, I have made the changes to the problem: #465
> docs: feedback about experimental features

- docs/guide/index.md
- pnpm-lock.yaml
> docs: add comment in create project guide

- docs/guide/env-and-mode.md
The example was applied to the problem #1376.
> docs: add import.meta.env.DEV example
